image:
  file: .gitpod.Dockerfile

tasks:
  - init: mvn -f p2composite-maven-plugin package -DskipTests

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - eamodio.gitlens
    - redhat.fabric8-analytics
